
package ec.edu.monster.ws.eurekabank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WSEurekaBank", targetNamespace = "http://ws.monster.edu.ec/", wsdlLocation = "https://javasoto.dr00p3r.top/WS_EurekaBank_SOAPJAVA_GR03/WSEurekaBank?wsdl")
public class WSEurekaBank_Service
    extends Service
{

    private final static URL WSEUREKABANK_WSDL_LOCATION;
    private final static WebServiceException WSEUREKABANK_EXCEPTION;
    private final static QName WSEUREKABANK_QNAME = new QName("http://ws.monster.edu.ec/", "WSEurekaBank");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://javasoto.dr00p3r.top/WS_EurekaBank_SOAPJAVA_GR03/WSEurekaBank?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSEUREKABANK_WSDL_LOCATION = url;
        WSEUREKABANK_EXCEPTION = e;
    }

    public WSEurekaBank_Service() {
        super(__getWsdlLocation(), WSEUREKABANK_QNAME);
    }

    public WSEurekaBank_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSEUREKABANK_QNAME, features);
    }

    public WSEurekaBank_Service(URL wsdlLocation) {
        super(wsdlLocation, WSEUREKABANK_QNAME);
    }

    public WSEurekaBank_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSEUREKABANK_QNAME, features);
    }

    public WSEurekaBank_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSEurekaBank_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSEurekaBank
     */
    @WebEndpoint(name = "WSEurekaBankPort")
    public WSEurekaBank getWSEurekaBankPort() {
        return super.getPort(new QName("http://ws.monster.edu.ec/", "WSEurekaBankPort"), WSEurekaBank.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSEurekaBank
     */
    @WebEndpoint(name = "WSEurekaBankPort")
    public WSEurekaBank getWSEurekaBankPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.monster.edu.ec/", "WSEurekaBankPort"), WSEurekaBank.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSEUREKABANK_EXCEPTION!= null) {
            throw WSEUREKABANK_EXCEPTION;
        }
        return WSEUREKABANK_WSDL_LOCATION;
    }

}
