/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.edu.monster.vista;

import ec.edu.monster.servicios.EuBankService;
import ec.edu.monster.ws.eurekabank.DatosCuenta;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dome
 */
public class Clients extends javax.swing.JPanel {

    private EuBankService euBankService = new EuBankService();
    /**
     * Creates new form Clients
     */
    public Clients() {
        initComponents();
        cargarDatos(); 
    }
    
    public void setEuBankService(EuBankService euBankService) {
        this.euBankService = euBankService;
        
        // AHORA que ya tenemos el servicio, cargamos los datos.
    }
    
    private void cargarDatos() {
        // Verificación por si algo falla
        if (this.euBankService == null) {
            System.err.println("Error: EuBankService no fue inyectado en el panel Clients.");
            return;
        }

        // 1. Definir las columnas
        String[] columnNames = {"Cuenta", "Cliente", "Moneda", "Estado", "Saldo"};
        
        // 2. Crear un modelo de tabla vacío
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            // Hacemos que las celdas no sean editables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            // 3. ¡Llamar al servicio SOAP!
            List<DatosCuenta> cuentas = this.euBankService.traerCuentasConClientes();

            // 4. Llenar el modelo con los datos
            for (DatosCuenta cuenta : cuentas) {
                Object[] row = new Object[] {
                    cuenta.getCodigo(),
                    cuenta.getNombreCliente(),
                    cuenta.getMoneda(),
                    cuenta.getEstado(),
                    cuenta.getSaldo() // El JTable sabe cómo mostrar BigDecimal
                };
                model.addRow(row);
            }
            
            // 5. Asignar el modelo a la tabla
            tableClients.getTable().setModel(model);

        } catch (Exception ex) {
            // Mostrar un error si el SOAP falla
            JOptionPane.showMessageDialog(this, "Error al cargar datos de clientes: " + ex.getMessage(), "Error de Conexión", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modernPanel2 = new ec.edu.monster.vista.ModernPanel();
        lblimagesulli = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        tableClients = new ec.edu.monster.vista.ModernTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(680, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        modernPanel2.setBackground(new java.awt.Color(219, 240, 245));
        modernPanel2.setBorderColor(new java.awt.Color(255, 255, 255));
        modernPanel2.setPanelBackground(new java.awt.Color(235, 247, 248));

        lblimagesulli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SulliGeneral.png"))); // NOI18N
        lblimagesulli.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblTitle.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(140, 201, 221));
        lblTitle.setText("Gestión de Cuentas");

        lblTitle1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(102, 102, 102));
        lblTitle1.setText("Administra y consulta las cuentas bancarias");

        javax.swing.GroupLayout modernPanel2Layout = new javax.swing.GroupLayout(modernPanel2);
        modernPanel2.setLayout(modernPanel2Layout);
        modernPanel2Layout.setHorizontalGroup(
            modernPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modernPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblimagesulli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modernPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblTitle1))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        modernPanel2Layout.setVerticalGroup(
            modernPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimagesulli)
            .addGroup(modernPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle1))
        );

        tableClients.setBackground(new java.awt.Color(255, 255, 255));
        tableClients.setBorder(null);
        tableClients.setBorderRadius(0);
        tableClients.setContainerBackground(new java.awt.Color(255, 255, 255));
        tableClients.setEvenRowColor(new java.awt.Color(242, 250, 253));
        tableClients.setHeaderBackground(new java.awt.Color(153, 214, 234));
        tableClients.setHoverRowColor(new java.awt.Color(204, 255, 255));
        tableClients.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tableClients.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tableClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modernPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(modernPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tableClients, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 570));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblimagesulli;
    private ec.edu.monster.vista.ModernPanel modernPanel2;
    private ec.edu.monster.vista.ModernTable tableClients;
    // End of variables declaration//GEN-END:variables
}
