//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaData", Namespace="http://schemas.datacontract.org/2004/07/WS_EuBank_SOAPDOTNET_GR03")]
    [System.SerializableAttribute()]
    public partial class CuentaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCliente {
            get {
                return this.EmailClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailClienteField, value) != true)) {
                    this.EmailClienteField = value;
                    this.RaisePropertyChanged("EmailCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoCliente {
            get {
                return this.TelefonoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoClienteField, value) != true)) {
                    this.TelefonoClienteField = value;
                    this.RaisePropertyChanged("TelefonoCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientoData", Namespace="http://schemas.datacontract.org/2004/07/WS_EuBank_SOAPDOTNET_GR03")]
    [System.SerializableAttribute()]
    public partial class MovimientoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SaldoActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCuenta {
            get {
                return this.CodigoCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCuentaField, value) != true)) {
                    this.CodigoCuentaField = value;
                    this.RaisePropertyChanged("CodigoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoActual {
            get {
                return this.SaldoActualField;
            }
            set {
                if ((this.SaldoActualField.Equals(value) != true)) {
                    this.SaldoActualField = value;
                    this.RaisePropertyChanged("SaldoActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoOperacion", Namespace="http://schemas.datacontract.org/2004/07/WS_EuBank_SOAPDOTNET_GR03")]
    [System.SerializableAttribute()]
    public partial class ResultadoOperacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovimientosService.IMovimientosService")]
    public interface IMovimientosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/GetDatosCuentas", ReplyAction="http://tempuri.org/IMovimientosService/GetDatosCuentasResponse")]
        CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.CuentaData[] GetDatosCuentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/GetDatosCuentas", ReplyAction="http://tempuri.org/IMovimientosService/GetDatosCuentasResponse")]
        System.Threading.Tasks.Task<CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.CuentaData[]> GetDatosCuentasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/GetMovimientos", ReplyAction="http://tempuri.org/IMovimientosService/GetMovimientosResponse")]
        CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.MovimientoData[] GetMovimientos(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/GetMovimientos", ReplyAction="http://tempuri.org/IMovimientosService/GetMovimientosResponse")]
        System.Threading.Tasks.Task<CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.MovimientoData[]> GetMovimientosAsync(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/ProcesarMovimiento", ReplyAction="http://tempuri.org/IMovimientosService/ProcesarMovimientoResponse")]
        CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.ResultadoOperacion ProcesarMovimiento(string tipo, string cuentaOrigen, string cuentaDestino, decimal importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/ProcesarMovimiento", ReplyAction="http://tempuri.org/IMovimientosService/ProcesarMovimientoResponse")]
        System.Threading.Tasks.Task<CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.ResultadoOperacion> ProcesarMovimientoAsync(string tipo, string cuentaOrigen, string cuentaDestino, decimal importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/GetTiposMovimiento", ReplyAction="http://tempuri.org/IMovimientosService/GetTiposMovimientoResponse")]
        string[] GetTiposMovimiento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/GetTiposMovimiento", ReplyAction="http://tempuri.org/IMovimientosService/GetTiposMovimientoResponse")]
        System.Threading.Tasks.Task<string[]> GetTiposMovimientoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovimientosServiceChannel : CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.IMovimientosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovimientosServiceClient : System.ServiceModel.ClientBase<CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.IMovimientosService>, CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.IMovimientosService {
        
        public MovimientosServiceClient() {
        }
        
        public MovimientosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovimientosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.CuentaData[] GetDatosCuentas() {
            return base.Channel.GetDatosCuentas();
        }
        
        public System.Threading.Tasks.Task<CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.CuentaData[]> GetDatosCuentasAsync() {
            return base.Channel.GetDatosCuentasAsync();
        }
        
        public CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.MovimientoData[] GetMovimientos(string cuenta) {
            return base.Channel.GetMovimientos(cuenta);
        }
        
        public System.Threading.Tasks.Task<CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.MovimientoData[]> GetMovimientosAsync(string cuenta) {
            return base.Channel.GetMovimientosAsync(cuenta);
        }
        
        public CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.ResultadoOperacion ProcesarMovimiento(string tipo, string cuentaOrigen, string cuentaDestino, decimal importe) {
            return base.Channel.ProcesarMovimiento(tipo, cuentaOrigen, cuentaDestino, importe);
        }
        
        public System.Threading.Tasks.Task<CLICON_EuBank_SOAPDOTNET_GR03.MovimientosService.ResultadoOperacion> ProcesarMovimientoAsync(string tipo, string cuentaOrigen, string cuentaDestino, decimal importe) {
            return base.Channel.ProcesarMovimientoAsync(tipo, cuentaOrigen, cuentaDestino, importe);
        }
        
        public string[] GetTiposMovimiento() {
            return base.Channel.GetTiposMovimiento();
        }
        
        public System.Threading.Tasks.Task<string[]> GetTiposMovimientoAsync() {
            return base.Channel.GetTiposMovimientoAsync();
        }
    }
}
