// <auto-generated />
namespace WS_EuBank_RESTDOTNET_GR03.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CreacionInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreacionInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202605180536383_CreacionInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
