//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimientosServiceRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaData", Namespace="http://schemas.datacontract.org/2004/07/WS_EuBank_SOAPDOTNET_GR03")]
    public partial class CuentaData : object
    {
        
        private string CodigoField;
        
        private string EmailClienteField;
        
        private string EstadoField;
        
        private string MonedaField;
        
        private string NombreClienteField;
        
        private decimal SaldoField;
        
        private string TelefonoClienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCliente
        {
            get
            {
                return this.EmailClienteField;
            }
            set
            {
                this.EmailClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoCliente
        {
            get
            {
                return this.TelefonoClienteField;
            }
            set
            {
                this.TelefonoClienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientoData", Namespace="http://schemas.datacontract.org/2004/07/WS_EuBank_SOAPDOTNET_GR03")]
    public partial class MovimientoData : object
    {
        
        private string CodigoCuentaField;
        
        private System.DateTime FechaField;
        
        private decimal ImporteField;
        
        private string NombreClienteField;
        
        private int NumeroField;
        
        private string ReferenciaField;
        
        private decimal SaldoActualField;
        
        private string TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCuenta
        {
            get
            {
                return this.CodigoCuentaField;
            }
            set
            {
                this.CodigoCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe
        {
            get
            {
                return this.ImporteField;
            }
            set
            {
                this.ImporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia
        {
            get
            {
                return this.ReferenciaField;
            }
            set
            {
                this.ReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoActual
        {
            get
            {
                return this.SaldoActualField;
            }
            set
            {
                this.SaldoActualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoOperacion", Namespace="http://schemas.datacontract.org/2004/07/WS_EuBank_SOAPDOTNET_GR03")]
    public partial class ResultadoOperacion : object
    {
        
        private int CodigoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovimientosServiceRef.IMovimientosService")]
    public interface IMovimientosService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/GetDatosCuentas", ReplyAction="http://tempuri.org/IMovimientosService/GetDatosCuentasResponse")]
        System.Threading.Tasks.Task<MovimientosServiceRef.CuentaData[]> GetDatosCuentasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/GetMovimientos", ReplyAction="http://tempuri.org/IMovimientosService/GetMovimientosResponse")]
        System.Threading.Tasks.Task<MovimientosServiceRef.MovimientoData[]> GetMovimientosAsync(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/ProcesarMovimiento", ReplyAction="http://tempuri.org/IMovimientosService/ProcesarMovimientoResponse")]
        System.Threading.Tasks.Task<MovimientosServiceRef.ResultadoOperacion> ProcesarMovimientoAsync(string tipo, string cuentaOrigen, string cuentaDestino, decimal importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientosService/GetTiposMovimiento", ReplyAction="http://tempuri.org/IMovimientosService/GetTiposMovimientoResponse")]
        System.Threading.Tasks.Task<string[]> GetTiposMovimientoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IMovimientosServiceChannel : MovimientosServiceRef.IMovimientosService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MovimientosServiceClient : System.ServiceModel.ClientBase<MovimientosServiceRef.IMovimientosService>, MovimientosServiceRef.IMovimientosService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MovimientosServiceClient() : 
                base(MovimientosServiceClient.GetDefaultBinding(), MovimientosServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMovimientosService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovimientosServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MovimientosServiceClient.GetBindingForEndpoint(endpointConfiguration), MovimientosServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovimientosServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MovimientosServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovimientosServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MovimientosServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovimientosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MovimientosServiceRef.CuentaData[]> GetDatosCuentasAsync()
        {
            return base.Channel.GetDatosCuentasAsync();
        }
        
        public System.Threading.Tasks.Task<MovimientosServiceRef.MovimientoData[]> GetMovimientosAsync(string cuenta)
        {
            return base.Channel.GetMovimientosAsync(cuenta);
        }
        
        public System.Threading.Tasks.Task<MovimientosServiceRef.ResultadoOperacion> ProcesarMovimientoAsync(string tipo, string cuentaOrigen, string cuentaDestino, decimal importe)
        {
            return base.Channel.ProcesarMovimientoAsync(tipo, cuentaOrigen, cuentaDestino, importe);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTiposMovimientoAsync()
        {
            return base.Channel.GetTiposMovimientoAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMovimientosService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMovimientosService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:62278/Services/MovimientosService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MovimientosServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMovimientosService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MovimientosServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMovimientosService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMovimientosService,
        }
    }
}
