
package ec.edu.monster.ws.eurekabank;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSEurekaBank", targetNamespace = "http://ws.monster.edu.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSEurekaBank {


    /**
     * 
     * @return
     *     returns java.util.List<ec.edu.monster.ws.eurekabank.DatosCuenta>
     */
    @WebMethod
    @WebResult(name = "GetDatosCuentasResult", targetNamespace = "")
    @RequestWrapper(localName = "traerCuentasConClientes", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.TraerCuentasConClientes")
    @ResponseWrapper(localName = "traerCuentasConClientesResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.TraerCuentasConClientesResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEurekaBank/traerCuentasConClientesRequest", output = "http://ws.monster.edu.ec/WSEurekaBank/traerCuentasConClientesResponse")
    public List<DatosCuenta> traerCuentasConClientes();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "tipoMovimiento", targetNamespace = "")
    @RequestWrapper(localName = "tipoMovimientosPermitidos", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.TipoMovimientosPermitidos")
    @ResponseWrapper(localName = "tipoMovimientosPermitidosResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.TipoMovimientosPermitidosResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEurekaBank/tipoMovimientosPermitidosRequest", output = "http://ws.monster.edu.ec/WSEurekaBank/tipoMovimientosPermitidosResponse")
    public List<String> tipoMovimientosPermitidos();

    /**
     * 
     * @param tipo
     * @param cuentaDestino
     * @param cuentaOrigen
     * @param importe
     * @return
     *     returns ec.edu.monster.ws.eurekabank.ResultadoOperacion
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "regMovimiento", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.RegMovimiento")
    @ResponseWrapper(localName = "regMovimientoResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.RegMovimientoResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEurekaBank/regMovimientoRequest", output = "http://ws.monster.edu.ec/WSEurekaBank/regMovimientoResponse")
    public ResultadoOperacion regMovimiento(
        @WebParam(name = "cuentaOrigen", targetNamespace = "")
        String cuentaOrigen,
        @WebParam(name = "cuentaDestino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "importe", targetNamespace = "")
        double importe);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "iniciarSesion", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.IniciarSesion")
    @ResponseWrapper(localName = "iniciarSesionResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.IniciarSesionResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEurekaBank/iniciarSesionRequest", output = "http://ws.monster.edu.ec/WSEurekaBank/iniciarSesionResponse")
    public boolean iniciarSesion(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena);

    /**
     * 
     * @param cuenta
     * @return
     *     returns java.util.List<ec.edu.monster.ws.eurekabank.MovimientoData>
     */
    @WebMethod
    @WebResult(name = "MovimientoData", targetNamespace = "")
    @RequestWrapper(localName = "traerMovimientos", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.TraerMovimientos")
    @ResponseWrapper(localName = "traerMovimientosResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.eurekabank.TraerMovimientosResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEurekaBank/traerMovimientosRequest", output = "http://ws.monster.edu.ec/WSEurekaBank/traerMovimientosResponse")
    public List<MovimientoData> traerMovimientos(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta);

}
